local _0x11 = {}

_0x11.Ancients = {
	["Batwing"] = {value=42,rarity="Ancient"},
	["Celestial"] = {value=2550,rarity="Ancient"},
	["Elderwood Scythe"] = {value=38,rarity="Ancient"},
	["Gingerscope"] = {value=16500,rarity="Ancient"},
	["Hallowscythe"] = {value=30,rarity="Ancient"},
	["Harvester"] = {value=250,rarity="Ancient"},
	["Icebreaker"] = {value=65,rarity="Ancient"},
	["Icepiercer"] = {value=160,rarity="Ancient"},
	["Icewing"] = {value=13,rarity="Ancient"},
	["Logchopper"] = {value=18,rarity="Ancient"},
	["Swirly Axe"] = {value=38,rarity="Ancient"},
	["Traveler's Axe"] = {value=8100,rarity="Ancient"},
	["Vampire's Axe"] = {value=1600,rarity="Ancient"},
}

_0x11.Chromas = {
	["Chroma Alienbeam"] = {value=24000,rarity="Chroma"},
	["Chroma Bauble"] = {value=34000,rarity="Chroma"},
	["Chroma Beachy"] = {value=1550,rarity="Chroma"},
	["Chroma Blizzard"] = {value=4400,rarity="Chroma"},
	["Chroma Boneblade"] = {value=22,rarity="Chroma"},
	["Chroma Candleflame"] = {value=40,rarity="Chroma"},
	["Chroma Constellation"] = {value=33000,rarity="Chroma"},
	["Chroma Cookiecane"] = {value=32,rarity="Chroma"},
	["Chroma Darkbringer"] = {value=65,rarity="Chroma"},
	["Chroma Deathshard"] = {value=35,rarity="Chroma"},
	["Chroma Elderwood Blade"] = {value=37,rarity="Chroma"},
	["Chroma Evergreen"] = {value=47000,rarity="Chroma"},
	["Chroma Evergun"] = {value=68000,rarity="Chroma"},
	["Chroma Fang"] = {value=32,rarity="Chroma"},
	["Chroma Fire Bat"] = {value=3,rarity="Chroma"},
	["Chroma Fire Bear"] = {value=3,rarity="Chroma"},
	["Chroma Fire Bunny"] = {value=3,rarity="Chroma"},
	["Chroma Fire Cat"] = {value=3,rarity="Chroma"},
	["Chroma Fire Dog"] = {value=3,rarity="Chroma"},
	["Chroma Fire Fox"] = {value=3,rarity="Chroma"},
	["Chroma Fire Pig"] = {value=3,rarity="Chroma"},
	["Chroma Gemstone"] = {value=32,rarity="Chroma"},
	["Chroma Gingerblade"] = {value=27,rarity="Chroma"},
	["Chroma Heart Wand"] = {value=4250,rarity="Chroma"},
	["Chroma Heat"] = {value=28,rarity="Chroma"},
	["Chroma Icecream"] = {value=2250,rarity="Chroma"},
	["Chroma Laser"] = {value=40,rarity="Chroma"},
	["Chroma Lightbringer"] = {value=60,rarity="Chroma"},
	["Chroma Luger"] = {value=50,rarity="Chroma"},
	["Chroma Ornament"] = {value=1825,rarity="Chroma"},
	["Chroma Raygun"] = {value=14000,rarity="Chroma"},
	["Chroma Sands"] = {value=1600,rarity="Chroma"},
	["Chroma Saw"] = {value=23,rarity="Chroma"},
	["Chroma Seer"] = {value=28,rarity="Chroma"},
	["Chroma Shark"] = {value=32,rarity="Chroma"},
	["Chroma Slasher"] = {value=32,rarity="Chroma"},
	["Chroma Snow Dagger"] = {value=2350,rarity="Chroma"},
	["Chroma Snowcannon"] = {value=7750,rarity="Chroma"},
	["Chroma Snowstorm"] = {value=4250,rarity="Chroma"},
	["Chroma Sunrise"] = {value=11250,rarity="Chroma"},
	["Chroma Sunset"] = {value=7250,rarity="Chroma"},
	["Chroma Sweet"] = {value=1725,rarity="Chroma"},
	["Chroma Swirly Gun"] = {value=35,rarity="Chroma"},
	["Chroma Tides"] = {value=27,rarity="Chroma"},
	["Chroma Traveler's Gun"] = {value=185000,rarity="Chroma"},
	["Chroma Treat"] = {value=1775,rarity="Chroma"},
	["Chroma Vampire's Gun"] = {value=29000,rarity="Chroma"},
	["Chroma Watergun"] = {value=2700,rarity="Chroma"},
}

_0x11.Godlies = {
	["Alienbeam"] = {value=2050,rarity="Godly"},
	["Amerilaser"] = {value=22,rarity="Godly"},
	["Australis"] = {value=140,rarity="Godly"},
	["Bat"] = {value=120,rarity="Godly"},
	["Battleaxe"] = {value=12,rarity="Godly"},
	["Battleaxe II"] = {value=17,rarity="Godly"},
	["Batwing"] = {value=1000000,rarity="Godly"},
	["Bauble"] = {value=675,rarity="Godly"},
	["Beachy"] = {value=105,rarity="Godly"},
	["Bioblade"] = {value=8,rarity="Godly"},
	["Black Luger"] = {value=1000000,rarity="Godly"},
	["Blaster"] = {value=17,rarity="Godly"},
	["Blizzard"] = {value=280,rarity="Godly"},
	["Bloom"] = {value=400,rarity="Godly"},
	["Blossom"] = {value=1370,rarity="Godly"},
	["Blue Seer"] = {value=3,rarity="Godly"},
	["Boneblade"] = {value=7,rarity="Godly"},
	["Borealis"] = {value=145,rarity="Godly"},
	["Candleflame"] = {value=33,rarity="Godly"},
	["Candy"] = {value=80,rarity="Godly"},
	["Chill"] = {value=10,rarity="Godly"},
	["Clockwork"] = {value=10,rarity="Godly"},
	["Constellation"] = {value=3200,rarity="Godly"},
	["Cookieblade"] = {value=3,rarity="Godly"},
	["Cookiecane"] = {value=13,rarity="Godly"},
	["Darkbringer"] = {value=33,rarity="Godly"},
	["Darkshot"] = {value=1800,rarity="Godly"},
	["Darksword"] = {value=1775,rarity="Godly"},
	["Deathshard"] = {value=13,rarity="Godly"},
	["Eggblade"] = {value=5,rarity="Godly"},
	["Elderwood Blade"] = {value=33,rarity="Godly"},
	["Elderwood Revolver"] = {value=33,rarity="Godly"},
	["Eternal"] = {value=7,rarity="Godly"},
	["Eternal II"] = {value=7,rarity="Godly"},
	["Eternal III"] = {value=8,rarity="Godly"},
	["Eternal IV"] = {value=8,rarity="Godly"},
	["Eternalcane"] = {value=13,rarity="Godly"},
	["Evergreen"] = {value=2900,rarity="Godly"},
	["Evergun"] = {value=3450,rarity="Godly"},
	["Fang"] = {value=10,rarity="Godly"},
	["Flames"] = {value=5,rarity="Godly"},
	["Flora"] = {value=410,rarity="Godly"},
	["Flowerwood"] = {value=260,rarity="Godly"},
	["Flowerwood Gun"] = {value=265,rarity="Godly"},
	["Frostbite"] = {value=7,rarity="Godly"},
	["Frostsaber"] = {value=10,rarity="Godly"},
	["Gemstone"] = {value=15,rarity="Godly"},
	["Ghostblade"] = {value=7,rarity="Godly"},
	["Ginger Luger"] = {value=17,rarity="Godly"},
	["Gingerblade"] = {value=13,rarity="Godly"},
	["Gingermint"] = {value=12,rarity="Godly"},
	["Green Luger"] = {value=23,rarity="Godly"},
	["Hallow's Blade"] = {value=8,rarity="Godly"},
	["Hallow's Edge"] = {value=8,rarity="Godly"},
	["Hallowgun"] = {value=20,rarity="Godly"},
	["Handsaw"] = {value=8,rarity="Godly"},
	["Heart Wand"] = {value=340,rarity="Godly"},
	["Heartblade"] = {value=65,rarity="Godly"},
	["Heat"] = {value=10,rarity="Godly"},
	["Ice Dragon"] = {value=7,rarity="Godly"},
	["Ice Shard"] = {value=7,rarity="Godly"},
	["Icebeam"] = {value=18,rarity="Godly"},
	["Iceblaster"] = {value=33,rarity="Godly"},
	["Icecream"] = {value=155,rarity="Godly"},
	["Iceflake"] = {value=15,rarity="Godly"},
	["Jinglegun"] = {value=13,rarity="Godly"},
	["Laser"] = {value=22,rarity="Godly"},
	["Lightbringer"] = {value=32,rarity="Godly"},
	["Luger"] = {value=18,rarity="Godly"},
	["Lugercane"] = {value=13,rarity="Godly"},
	["Makeshift"] = {value=33,rarity="Godly"},
	["Minty"] = {value=13,rarity="Godly"},
	["Mortal Blade"] = {value=1000000,rarity="Godly"},
	["Nebula"] = {value=13,rarity="Godly"},
	["Nightblade"] = {value=20,rarity="Godly"},
	["Ocean"] = {value=285,rarity="Godly"},
	["Old Glory"] = {value=15,rarity="Godly"},
	["Orange Seer"] = {value=2,rarity="Godly"},
	["Ornament"] = {value=105,rarity="Godly"},
	["Pearl"] = {value=75,rarity="Godly"},
	["Pearlshine"] = {value=80,rarity="Godly"},
	["Peppermint"] = {value=4,rarity="Godly"},
	["Phantom"] = {value=35,rarity="Godly"},
	["Pixel"] = {value=17,rarity="Godly"},
	["Plasmabeam"] = {value=18,rarity="Godly"},
	["Plasmablade"] = {value=15,rarity="Godly"},
	["Prismatic"] = {value=7,rarity="Godly"},
	["Pumpking"] = {value=7,rarity="Godly"},
	["Purple Seer"] = {value=3,rarity="Godly"},
	["Rainbow"] = {value=410,rarity="Godly"},
	["Rainbow Gun"] = {value=420,rarity="Godly"},
	["Raygun"] = {value=1750,rarity="Godly"},
	["Red Luger"] = {value=35,rarity="Godly"},
	["Red Seer"] = {value=3,rarity="Godly"},
	["Sakura"] = {value=1360,rarity="Godly"},
	["Sands"] = {value=105,rarity="Godly"},
	["Saw"] = {value=7,rarity="Godly"},
	["Seer"] = {value=3,rarity="Godly"},
	["Shark"] = {value=20,rarity="Godly"},
	["Slasher"] = {value=15,rarity="Godly"},
	["Snow Dagger"] = {value=175,rarity="Godly"},
	["Snowcannon"] = {value=675,rarity="Godly"},
	["Snowflake"] = {value=5,rarity="Godly"},
	["Snowstorm"] = {value=280,rarity="Godly"},
	["Soul"] = {value=655,rarity="Godly"},
	["Spectre"] = {value=35,rarity="Godly"},
	["Spider"] = {value=10,rarity="Godly"},
	["Spirit"] = {value=645,rarity="Godly"},
	["Sugar"] = {value=32,rarity="Godly"},
	["Sunrise"] = {value=1100,rarity="Godly"},
	["Sunset"] = {value=675,rarity="Godly"},
	["Sweet"] = {value=150,rarity="Godly"},
	["Swirly Blade"] = {value=12,rarity="Godly"},
	["Swirly Gun"] = {value=18,rarity="Godly"},
	["Tides"] = {value=10,rarity="Godly"},
	["Traveler's Gun"] = {value=5500,rarity="Godly"},
	["Treat"] = {value=155,rarity="Godly"},
	["Turkey"] = {value=2000,rarity="Godly"},
	["Vampire's Edge"] = {value=15,rarity="Godly"},
	["Vampire's Gun"] = {value=2100,rarity="Godly"},
	["Virtual"] = {value=13,rarity="Godly"},
	["Watergun"] = {value=175,rarity="Godly"},
	["Waves"] = {value=280,rarity="Godly"},
	["Winter's Edge"] = {value=5,rarity="Godly"},
	["Xenoknife"] = {value=405,rarity="Godly"},
	["Xenoshot"] = {value=405,rarity="Godly"},
	["Xmas"] = {value=7,rarity="Godly"},
	["Yellow Seer"] = {value=2,rarity="Godly"},
}

_0x11.Legendaries = {
	["Aquarium (Gun)"] = {value=75,rarity="Legendary"},
	["Aquarium (Knife)"] = {value=50,rarity="Legendary"},
	["Arctic (Gun)"] = {value=10,rarity="Legendary"},
	["Arctic (Knife)"] = {value=100,rarity="Legendary"},
	["Aurora (Gun)"] = {value=45,rarity="Legendary"},
	["Aurora (Knife)"] = {value=3,rarity="Legendary"},
	["Beach"] = {value=35,rarity="Legendary"},
	["Blue Elite"] = {value=3,rarity="Legendary"},
	["Blue Scratch"] = {value=2,rarity="Legendary"},
	["Broken"] = {value=7,rarity="Legendary"},
	["Bubbles"] = {value=50,rarity="Legendary"},
	["Bunnies"] = {value=4,rarity="Legendary"},
	["Cavern (Gun)"] = {value=1,rarity="Legendary"},
	["Cavern (Knife)"] = {value=7,rarity="Legendary"},
	["Chromatic (Gun)"] = {value=100,rarity="Legendary"},
	["Chromatic (Knife)"] = {value=1,rarity="Legendary"},
	["Cotton Candy"] = {value=35,rarity="Legendary"},
	["Cupid"] = {value=50,rarity="Legendary"},
	["Cursed (Gun)"] = {value=75,rarity="Legendary"},
	["Cursed (Knife)"] = {value=100,rarity="Legendary"},
	["Elite"] = {value=24,rarity="Legendary"},
	["Emerald"] = {value=100,rarity="Legendary"},
	["Energized (Gun)"] = {value=2,rarity="Legendary"},
	["Energized (Knife)"] = {value=100,rarity="Legendary"},
	["Fade"] = {value=32,rarity="Legendary"},
	["Frostfade (Gun)"] = {value=75,rarity="Legendary"},
	["Frostfade (Knife)"] = {value=2,rarity="Legendary"},
	["Frozen (Gun)"] = {value=100,rarity="Legendary"},
	["Frozen (Knife)"] = {value=75,rarity="Legendary"},
	["Fusion"] = {value=32,rarity="Legendary"},
	["Ghost (Gun)"] = {value=2,rarity="Legendary"},
	["Ghost (Knife)"] = {value=5,rarity="Legendary"},
	["Ginger (Gun)"] = {value=5,rarity="Legendary"},
	["Ginger (Knife)"] = {value=50,rarity="Legendary"},
	["Green Elite"] = {value=3,rarity="Legendary"},
	["Green Fire"] = {value=100,rarity="Legendary"},
	["Icecracker"] = {value=1,rarity="Legendary"},
	["Icedriller"] = {value=5,rarity="Legendary"},
	["JD"] = {value=28,rarity="Legendary"},
	["Latte (Gun)"] = {value=140,rarity="Legendary"},
	["Latte (Knife)"] = {value=140,rarity="Legendary"},
	["Midnight"] = {value=75,rarity="Legendary"},
	["Nightsky"] = {value=5,rarity="Legendary"},
	["Nightstar"] = {value=100,rarity="Legendary"},
	["Overseer (Gun)"] = {value=100,rarity="Legendary"},
	["Overseer (Knife)"] = {value=32,rarity="Legendary"},
	["Palms (Gun)"] = {value=75,rarity="Legendary"},
	["Palms (Knife)"] = {value=50,rarity="Legendary"},
	["Plasmite"] = {value=32,rarity="Legendary"},
	["Predator (Gun)"] = {value=32,rarity="Legendary"},
	["Predator (Knife)"] = {value=100,rarity="Legendary"},
	["Red Fire"] = {value=1,rarity="Legendary"},
	["Red Scratch"] = {value=4,rarity="Legendary"},
	["Ripper (Gun)"] = {value=50,rarity="Legendary"},
	["Ripper (Knife)"] = {value=100,rarity="Legendary"},
	["Rune"] = {value=32,rarity="Legendary"},
	["Rupture"] = {value=100,rarity="Legendary"},
	["Santa's Magic"] = {value=3,rarity="Legendary"},
	["Santa's Spirit"] = {value=3,rarity="Legendary"},
	["Shiny"] = {value=32,rarity="Legendary"},
	["Skulls"] = {value=4,rarity="Legendary"},
	["Sparkle"] = {value=75,rarity="Legendary"},
	["Spectral (Gun)"] = {value=3,rarity="Legendary"},
	["Spectral (Knife)"] = {value=50,rarity="Legendary"},
	["Splash (Gun)"] = {value=24,rarity="Legendary"},
	["Splash (Knife)"] = {value=32,rarity="Legendary"},
	["Traveler (Gun)"] = {value=50,rarity="Legendary"},
	["Traveler (Knife)"] = {value=3,rarity="Legendary"},
	["Tree (Gun)"] = {value=100,rarity="Legendary"},
	["Tree (Knife)"] = {value=100,rarity="Legendary"},
	["Universe"] = {value=32,rarity="Legendary"},
	["Vampire (Gun)"] = {value=45,rarity="Legendary"},
	["Vampire (Knife)"] = {value=3,rarity="Legendary"},
	["Viper"] = {value=32,rarity="Legendary"},
	["Web"] = {value=100,rarity="Legendary"},
	["Witched"] = {value=3,rarity="Legendary"},
}

_0x11.Rares = {
	["Abstract"] = {value=12,rarity="Rare"},
	["Ace"] = {value=12,rarity="Rare"},
	["Aurora (Gun)"] = {value=1,rarity="Rare"},
	["Aurora (Knife)"] = {value=7,rarity="Rare"},
	["Bacon"] = {value=12,rarity="Rare"},
	["Bats"] = {value=2,rarity="Rare"},
	["Bio"] = {value=24,rarity="Rare"},
	["Black"] = {value=12,rarity="Rare"},
	["Bones (Knife)"] = {value=24,rarity="Rare"},
	["Butterflies"] = {value=25,rarity="Rare"},
	["Candleflame (Gun)"] = {value=25,rarity="Rare"},
	["Candy Swirl (Gun)"] = {value=2,rarity="Rare"},
	["Candy Swirl (Knife)"] = {value=1,rarity="Rare"},
	["Cane (Gun) [XMAS2015]"] = {value=100,rarity="Rare"},
	["Cane (Gun) [XMAS2018]"] = {value=75,rarity="Rare"},
	["Cane (Knife) [XMAS2015]"] = {value=100,rarity="Rare"},
	["Cane (Knife) [XMAS2018]"] = {value=525,rarity="Rare"},
	["Curse"] = {value=24,rarity="Rare"},
	["Damp"] = {value=25,rarity="Rare"},
	["Darkgun"] = {value=1,rarity="Rare"},
	["Darkknife"] = {value=70,rarity="Rare"},
	["Deep Sea"] = {value=9,rarity="Rare"},
	["Dungeon"] = {value=150,rarity="Rare"},
	["Floral (Gun)"] = {value=16,rarity="Rare"},
	["Floral (Knife)"] = {value=10,rarity="Rare"},
	["Frostflame (Gun)"] = {value=24,rarity="Rare"},
	["Frostflame (Knife)"] = {value=25,rarity="Rare"},
	["Galactic"] = {value=12,rarity="Rare"},
	["Galaxy"] = {value=12,rarity="Rare"},
	["Ghastly (Gun)"] = {value=7,rarity="Rare"},
	["Ghastly (Knife)"] = {value=50,rarity="Rare"},
	["Ghostfire"] = {value=10,rarity="Rare"},
	["Ghosts (Gun)"] = {value=24,rarity="Rare"},
	["Ginger (Gun)"] = {value=100,rarity="Rare"},
	["Ginger (Knife)"] = {value=100,rarity="Rare"},
	["Gingerbread"] = {value=1,rarity="Rare"},
	["Gingerbread (Gun)"] = {value=100,rarity="Rare"},
	["Gingerbread (Knife)"] = {value=25,rarity="Rare"},
	["Gingercookie (Gun)"] = {value=16,rarity="Rare"},
	["Gingercookie (Knife)"] = {value=24,rarity="Rare"},
	["Green Marble"] = {value=2,rarity="Rare"},
	["Hacker"] = {value=12,rarity="Rare"},
	["Heart"] = {value=25,rarity="Rare"},
	["Heartbreak"] = {value=16,rarity="Rare"},
	["Hologram (Gun)"] = {value=24,rarity="Rare"},
	["Hologram (Knife)"] = {value=16,rarity="Rare"},
	["Ice Camo"] = {value=50,rarity="Rare"},
	["Icicles (Gun)"] = {value=3,rarity="Rare"},
	["Icicles (Knife)"] = {value=75,rarity="Rare"},
	["Imbued"] = {value=12,rarity="Rare"},
	["Jack"] = {value=3,rarity="Rare"},
	["Korblox"] = {value=12,rarity="Rare"},
	["Kraken"] = {value=16,rarity="Rare"},
	["Krypto"] = {value=12,rarity="Rare"},
	["Logcutter"] = {value=50,rarity="Rare"},
	["Magma"] = {value=3,rarity="Rare"},
	["Magma (Gun)"] = {value=13,rarity="Rare"},
	["Magma (Knife)"] = {value=75,rarity="Rare"},
	["Makeshift (Knife)"] = {value=35,rarity="Rare"},
	["Molten (Gun)"] = {value=50,rarity="Rare"},
	["Molten (Knife)"] = {value=50,rarity="Rare"},
	["Monster"] = {value=1,rarity="Rare"},
	["Mummy"] = {value=100,rarity="Rare"},
	["Musical"] = {value=12,rarity="Rare"},
	["Neon [SUMMER2025]"] = {value=16,rarity="Rare"},
	["Neon [XMAS2023]"] = {value=25,rarity="Rare"},
	["Nether"] = {value=25,rarity="Rare"},
	["Nightfire"] = {value=12,rarity="Rare"},
	["Nova"] = {value=12,rarity="Rare"},
	["Nuke"] = {value=75,rarity="Rare"},
	["Orange Marble"] = {value=2,rarity="Rare"},
	["Painted (Knife)"] = {value=25,rarity="Rare"},
	["Pier"] = {value=24,rarity="Rare"},
	["Pop Art (Gun)"] = {value=16,rarity="Rare"},
	["Pop Art (Knife)"] = {value=24,rarity="Rare"},
	["Portal (Knife)"] = {value=16,rarity="Rare"},
	["Purple"] = {value=12,rarity="Rare"},
	["Rainbow (Gun)"] = {value=12,rarity="Rare"},
	["Rainbow (Knife)"] = {value=12,rarity="Rare"},
	["Ritual"] = {value=16,rarity="Rare"},
	["Robot"] = {value=16,rarity="Rare"},
	["Sharky"] = {value=16,rarity="Rare"},
	["Silent Night (Gun)"] = {value=12,rarity="Rare"},
	["Silent Night (Knife)"] = {value=50,rarity="Rare"},
	["Sleigh"] = {value=16,rarity="Rare"},
	["Snakebite (Gun)"] = {value=1,rarity="Rare"},
	["Snakebite (Knife)"] = {value=3,rarity="Rare"},
	["Snowflake"] = {value=16,rarity="Rare"},
	["Snowflakes"] = {value=12,rarity="Rare"},
	["Snowglobe"] = {value=16,rarity="Rare"},
	["Snowy"] = {value=75,rarity="Rare"},
	["Space"] = {value=12,rarity="Rare"},
	["Spearmint (Gun)"] = {value=24,rarity="Rare"},
	["Spearmint (Knife)"] = {value=16,rarity="Rare"},
	["Spectrum"] = {value=12,rarity="Rare"},
	["Spitfire"] = {value=25,rarity="Rare"},
	["Spring"] = {value=16,rarity="Rare"},
	["Squire"] = {value=12,rarity="Rare"},
	["Starry (Gun)"] = {value=22,rarity="Rare"},
	["Starry (Knife)"] = {value=100,rarity="Rare"},
	["Storm"] = {value=25,rarity="Rare"},
	["Sun"] = {value=2,rarity="Rare"},
	["Sunny"] = {value=24,rarity="Rare"},
	["Sunset"] = {value=24,rarity="Rare"},
	["Swirl"] = {value=20,rarity="Rare"},
	["Toxic (Gun)"] = {value=2,rarity="Rare"},
	["Toxic (Knife)"] = {value=5,rarity="Rare"},
	["Tree (2023)"] = {value=24,rarity="Rare"},
	["Tree (Gun)"] = {value=16,rarity="Rare"},
	["Tree (Knife)"] = {value=24,rarity="Rare"},
	["Tropical"] = {value=24,rarity="Rare"},
	["Vampire (Gun)"] = {value=3,rarity="Rare"},
	["Vampire (Knife)"] = {value=1,rarity="Rare"},
	["Vortex"] = {value=12,rarity="Rare"},
	["Watcher (Gun)"] = {value=20,rarity="Rare"},
	["Watcher (Knife)"] = {value=75,rarity="Rare"},
	["Waves"] = {value=16,rarity="Rare"},
	["Wraith (Gun)"] = {value=25,rarity="Rare"},
	["Wraith (Knife)"] = {value=5,rarity="Rare"},
	["Xeno (Gun)"] = {value=16,rarity="Rare"},
	["Xeno (Knife)"] = {value=24,rarity="Rare"},
	["Yummy"] = {value=16,rarity="Rare"},
	["Zombified"] = {value=30,rarity="Rare"},
	["iRevolver"] = {value=12,rarity="Rare"},
}

_0x11.Uncommons = {
	["Abduction"] = {value=6,rarity="Uncommon"},
	["Adurite (Gun)"] = {value=4,rarity="Uncommon"},
	["Adurite (Knife)"] = {value=4,rarity="Uncommon"},
	["Biogun"] = {value=4,rarity="Uncommon"},
	["Blossom"] = {value=6,rarity="Uncommon"},
	["Blue"] = {value=4,rarity="Uncommon"},
	["Bluesteel (Gun)"] = {value=4,rarity="Uncommon"},
	["Bluesteel (Knife)"] = {value=4,rarity="Uncommon"},
	["Bones"] = {value=210,rarity="Uncommon"},
	["Bones (Knife)"] = {value=6,rarity="Uncommon"},
	["Brains"] = {value=135,rarity="Uncommon"},
	["Brains (2022)"] = {value=9,rarity="Uncommon"},
	["Branches"] = {value=50,rarity="Uncommon"},
	["Brush"] = {value=4,rarity="Uncommon"},
	["Camo (Gun)"] = {value=4,rarity="Uncommon"},
	["Camo (Knife)"] = {value=4,rarity="Uncommon"},
	["Canes (Gun)"] = {value=8,rarity="Uncommon"},
	["Canes (Knife)"] = {value=9,rarity="Uncommon"},
	["Carrot"] = {value=9,rarity="Uncommon"},
	["Carrot (Gun)"] = {value=9,rarity="Uncommon"},
	["Carrot (Knife)"] = {value=9,rarity="Uncommon"},
	["Caution"] = {value=4,rarity="Uncommon"},
	["Checkers"] = {value=9,rarity="Uncommon"},
	["Cheddar"] = {value=4,rarity="Uncommon"},
	["Cheesy"] = {value=4,rarity="Uncommon"},
	["Circuit"] = {value=4,rarity="Uncommon"},
	["Clown (Gun)"] = {value=9,rarity="Uncommon"},
	["Cookie (Gun)"] = {value=8,rarity="Uncommon"},
	["Cookie (Knife)"] = {value=1,rarity="Uncommon"},
	["Decorated"] = {value=9,rarity="Uncommon"},
	["Doge"] = {value=4,rarity="Uncommon"},
	["Donut"] = {value=6,rarity="Uncommon"},
	["Eclipse"] = {value=9,rarity="Uncommon"},
	["Eyes"] = {value=9,rarity="Uncommon"},
	["Fall Camo"] = {value=9,rarity="Uncommon"},
	["Fireplace"] = {value=8,rarity="Uncommon"},
	["Floatie"] = {value=9,rarity="Uncommon"},
	["Floral"] = {value=9,rarity="Uncommon"},
	["Forest"] = {value=8,rarity="Uncommon"},
	["Frosty"] = {value=8,rarity="Uncommon"},
	["Frozen (Gun)"] = {value=3,rarity="Uncommon"},
	["Frozen (Knife)"] = {value=1,rarity="Uncommon"},
	["Future"] = {value=9,rarity="Uncommon"},
	["Ghostly"] = {value=6,rarity="Uncommon"},
	["Ghosts (Knife)"] = {value=6,rarity="Uncommon"},
	["Gifted"] = {value=100,rarity="Uncommon"},
	["Gingerbread (Gun) [XMAS2019]"] = {value=1,rarity="Uncommon"},
	["Gingerbread (Gun) [XMAS2020]"] = {value=3,rarity="Uncommon"},
	["Gingerbread (Gun) [XMAS2021]"] = {value=9,rarity="Uncommon"},
	["Gingerbread (Gun) [XMAS2025]"] = {value=9,rarity="Uncommon"},
	["Gingerbread (Knife) [XMAS2019]"] = {value=85,rarity="Uncommon"},
	["Gingerbread (Knife) [XMAS2020]"] = {value=10,rarity="Uncommon"},
	["Gingerbread (Knife) [XMAS2025]"] = {value=6,rarity="Uncommon"},
	["Gingerheart"] = {value=16,rarity="Uncommon"},
	["Glowy"] = {value=9,rarity="Uncommon"},
	["Gothic (Gun)"] = {value=7,rarity="Uncommon"},
	["Gothic (Knife)"] = {value=100,rarity="Uncommon"},
	["Graffiti"] = {value=3,rarity="Uncommon"},
	["Hazard (Gun)"] = {value=5,rarity="Uncommon"},
	["Hazard (Knife)"] = {value=24,rarity="Uncommon"},
	["Hazmat"] = {value=4,rarity="Uncommon"},
	["High Tech"] = {value=3,rarity="Uncommon"},
	["Hive"] = {value=4,rarity="Uncommon"},
	["Holly (Gun)"] = {value=1,rarity="Uncommon"},
	["Holly (Knife)"] = {value=8,rarity="Uncommon"},
	["Jellyfish"] = {value=6,rarity="Uncommon"},
	["Jigsaw"] = {value=4,rarity="Uncommon"},
	["Lantern"] = {value=3,rarity="Uncommon"},
	["Lava (Gun)"] = {value=6,rarity="Uncommon"},
	["Lava (Knife)"] = {value=9,rarity="Uncommon"},
	["Leaves"] = {value=6,rarity="Uncommon"},
	["Lights (Gun)"] = {value=2,rarity="Uncommon"},
	["Lights (Knife)"] = {value=1,rarity="Uncommon"},
	["Love (Gun)"] = {value=16,rarity="Uncommon"},
	["Lucky"] = {value=4,rarity="Uncommon"},
	["Marble"] = {value=8,rarity="Uncommon"},
	["Marina"] = {value=4,rarity="Uncommon"},
	["Meadow"] = {value=9,rarity="Uncommon"},
	["Melon"] = {value=4,rarity="Uncommon"},
	["Melon [SUMMER2023]"] = {value=8,rarity="Uncommon"},
	["Meltdown"] = {value=2,rarity="Uncommon"},
	["Missing"] = {value=4,rarity="Uncommon"},
	["Mistletoe (Gun)"] = {value=24,rarity="Uncommon"},
	["Mistletoe (Knife)"] = {value=9,rarity="Uncommon"},
	["Monster"] = {value=9,rarity="Uncommon"},
	["Moonlight"] = {value=1,rarity="Uncommon"},
	["Moons"] = {value=1,rarity="Uncommon"},
	["Moons (2024)"] = {value=9,rarity="Uncommon"},
	["Mummy (2017)"] = {value=20,rarity="Uncommon"},
	["Mummy (Gun) [HALLOWS2018]"] = {value=2,rarity="Uncommon"},
	["Mummy (Gun) [HALLOWS2020]"] = {value=9,rarity="Uncommon"},
	["Mummy (Knife) [HALLOWS2018]"] = {value=1,rarity="Uncommon"},
	["Mummy (Knife) [HALLOWS2020]"] = {value=8,rarity="Uncommon"},
	["Neopolitan"] = {value=9,rarity="Uncommon"},
	["Night"] = {value=9,rarity="Uncommon"},
	["Nutcracker"] = {value=100,rarity="Uncommon"},
	["Ornaments"] = {value=6,rarity="Uncommon"},
	["Painted (Gun)"] = {value=9,rarity="Uncommon"},
	["Paper"] = {value=4,rarity="Uncommon"},
	["Paws"] = {value=6,rarity="Uncommon"},
	["Pink"] = {value=4,rarity="Uncommon"},
	["Pirate"] = {value=4,rarity="Uncommon"},
	["Polar Bear"] = {value=9,rarity="Uncommon"},
	["Pool"] = {value=9,rarity="Uncommon"},
	["Pool Noodle"] = {value=25,rarity="Uncommon"},
	["Popsicle"] = {value=9,rarity="Uncommon"},
	["Popsicle (Gun)"] = {value=6,rarity="Uncommon"},
	["Portal (Gun)"] = {value=6,rarity="Uncommon"},
	["Potion (2017)"] = {value=3,rarity="Uncommon"},
	["Potion (Gun)"] = {value=2,rarity="Uncommon"},
	["Potion (Knife)"] = {value=2,rarity="Uncommon"},
	["Pumpkin (2025)"] = {value=9,rarity="Uncommon"},
	["Pumpkin (Knife)"] = {value=6,rarity="Uncommon"},
	["Pumpkin Patch"] = {value=6,rarity="Uncommon"},
	["Pumpkin Pie"] = {value=2,rarity="Uncommon"},
	["Red"] = {value=4,rarity="Uncommon"},
	["Retro"] = {value=6,rarity="Uncommon"},
	["Rose"] = {value=16,rarity="Uncommon"},
	["Sketch"] = {value=4,rarity="Uncommon"},
	["Skulls"] = {value=15,rarity="Uncommon"},
	["Snowflake (Gun) [XMAS2018]"] = {value=8,rarity="Uncommon"},
	["Snowflake (Gun) [XMAS2022]"] = {value=9,rarity="Uncommon"},
	["Snowflake (Knife) [XMAS2018]"] = {value=55,rarity="Uncommon"},
	["Snowflake (Knife) [XMAS2022]"] = {value=25,rarity="Uncommon"},
	["Snowman (2023)"] = {value=9,rarity="Uncommon"},
	["Snowman (2024)"] = {value=6,rarity="Uncommon"},
	["Snowman (Gun) [XMAS2015]"] = {value=100,rarity="Uncommon"},
	["Snowman (Gun) [XMAS2021]"] = {value=5,rarity="Uncommon"},
	["Snowman (Knife) [XMAS2015]"] = {value=100,rarity="Uncommon"},
	["Snowman (Knife) [XMAS2021]"] = {value=8,rarity="Uncommon"},
	["Snowy"] = {value=100,rarity="Uncommon"},
	["Soda"] = {value=4,rarity="Uncommon"},
	["Soda (Gun)"] = {value=9,rarity="Uncommon"},
	["Soda (Knife)"] = {value=6,rarity="Uncommon"},
	["Stalker"] = {value=4,rarity="Uncommon"},
	["Starry"] = {value=6,rarity="Uncommon"},
	["Stars (Gun)"] = {value=9,rarity="Uncommon"},
	["Stars (Knife)"] = {value=2,rarity="Uncommon"},
	["Steel (Gun)"] = {value=8,rarity="Uncommon"},
	["Steel (Knife)"] = {value=50,rarity="Uncommon"},
	["Stockings (Gun)"] = {value=9,rarity="Uncommon"},
	["Stockings (Knife)"] = {value=9,rarity="Uncommon"},
	["Sweater"] = {value=9,rarity="Uncommon"},
	["Sweater (Gun) [XMAS2018]"] = {value=9,rarity="Uncommon"},
	["Sweater (Gun) [XMAS2025]"] = {value=6,rarity="Uncommon"},
	["Sweater (Knife) [XMAS2018]"] = {value=60,rarity="Uncommon"},
	["Sweater (Knife) [XMAS2025]"] = {value=9,rarity="Uncommon"},
	["Tiger"] = {value=4,rarity="Uncommon"},
	["Treats (Gun)"] = {value=9,rarity="Uncommon"},
	["Treats (Knife)"] = {value=6,rarity="Uncommon"},
	["Tree (2017)"] = {value=9,rarity="Uncommon"},
	["Tree (2021)"] = {value=2,rarity="Uncommon"},
	["Turtle"] = {value=6,rarity="Uncommon"},
	["Turtles"] = {value=9,rarity="Uncommon"},
	["Vampire"] = {value=1,rarity="Uncommon"},
	["Void"] = {value=12,rarity="Uncommon"},
	["Wanwood"] = {value=4,rarity="Uncommon"},
	["Webs"] = {value=3,rarity="Uncommon"},
	["Witch's Brew"] = {value=6,rarity="Uncommon"},
	["Witchbrew"] = {value=9,rarity="Uncommon"},
	["Wolf"] = {value=1,rarity="Uncommon"},
	["Wooden"] = {value=4,rarity="Uncommon"},
	["Wraiths (Gun)"] = {value=9,rarity="Uncommon"},
	["Wraiths (Knife)"] = {value=25,rarity="Uncommon"},
	["Wrap (Gun)"] = {value=12,rarity="Uncommon"},
	["Wrap (Knife)"] = {value=12,rarity="Uncommon"},
	["Wrapped (Gun) [XMAS2015]"] = {value=100,rarity="Uncommon"},
	["Wrapped (Gun) [XMAS2024]"] = {value=8,rarity="Uncommon"},
	["Wrapped (Knife) [XMAS2015]"] = {value=100,rarity="Uncommon"},
	["Wrapped (Knife) [XMAS2024]"] = {value=6,rarity="Uncommon"},
	["Wreaths"] = {value=6,rarity="Uncommon"},
	["Zombie"] = {value=7,rarity="Uncommon"},
	["Zombie (2023)"] = {value=3,rarity="Uncommon"},
	["Zombie (Gun)"] = {value=5,rarity="Uncommon"},
	["Zombie (Knife)"] = {value=1,rarity="Uncommon"},
	["Zombified (Gun)"] = {value=15,rarity="Uncommon"},
	["Zombified (Knife)"] = {value=120,rarity="Uncommon"},
}

_0x11.Commons = {
	["2015"] = {value=100,rarity="Common"},
	["8Bit"] = {value=1,rarity="Common"},
	["Alex"] = {value=4,rarity="Common"},
	["Aliens"] = {value=3,rarity="Common"},
	["Apocalypse (Gun)"] = {value=3,rarity="Common"},
	["Apocalypse (Knife)"] = {value=100,rarity="Common"},
	["Aqua"] = {value=1,rarity="Common"},
	["Asteroid"] = {value=2,rarity="Common"},
	["Balloons"] = {value=2,rarity="Common"},
	["Bats (2020)"] = {value=3,rarity="Common"},
	["Bats (Gun) [HALLOWS2018]"] = {value=1,rarity="Common"},
	["Bats (Gun) [HALLOWS2024]"] = {value=3,rarity="Common"},
	["Bats (Knife) [HALLOWS2018]"] = {value=240,rarity="Common"},
	["Bats (Knife) [HALLOWS2024]"] = {value=2,rarity="Common"},
	["Bells"] = {value=2,rarity="Common"},
	["Big Kill"] = {value=1,rarity="Common"},
	["Bit"] = {value=1,rarity="Common"},
	["Bleached"] = {value=1,rarity="Common"},
	["Blossom"] = {value=100,rarity="Common"},
	["Bones"] = {value=100,rarity="Common"},
	["Borders"] = {value=1,rarity="Common"},
	["Brains"] = {value=100,rarity="Common"},
	["Brown"] = {value=1,rarity="Common"},
	["Bunny"] = {value=100,rarity="Common"},
	["Candied (Gun)"] = {value=3,rarity="Common"},
	["Candied (Knife)"] = {value=6,rarity="Common"},
	["Candle"] = {value=3,rarity="Common"},
	["Candles"] = {value=3,rarity="Common"},
	["Candy Corn (2019)"] = {value=12,rarity="Common"},
	["Candy Corn (Gun) [HALLOWS2020]"] = {value=2,rarity="Common"},
	["Candy Corn (Gun) [HALLOWS2022]"] = {value=3,rarity="Common"},
	["Candy Corn (Gun) [HALLOWS2024]"] = {value=2,rarity="Common"},
	["Candy Corn (Gun) [HALLOWS2025]"] = {value=3,rarity="Common"},
	["Candy Corn (Knife) [HALLOWS2020]"] = {value=3,rarity="Common"},
	["Candy Corn (Knife) [HALLOWS2022]"] = {value=2,rarity="Common"},
	["Candy Corn (Knife) [HALLOWS2024]"] = {value=3,rarity="Common"},
	["Candy Corn (Knife) [HALLOWS2025]"] = {value=2,rarity="Common"},
	["CandyCorn (2017)"] = {value=25,rarity="Common"},
	["Cane (Gun)"] = {value=16,rarity="Common"},
	["Cane (Knife)"] = {value=3,rarity="Common"},
	["Cardboard"] = {value=1,rarity="Common"},
	["Carrot"] = {value=100,rarity="Common"},
	["Carrots"] = {value=3,rarity="Common"},
	["Carved (Gun)"] = {value=3,rarity="Common"},
	["Carved (Knife)"] = {value=2,rarity="Common"},
	["Cat"] = {value=3,rarity="Common"},
	["Cats"] = {value=3,rarity="Common"},
	["Cherries"] = {value=2,rarity="Common"},
	["Cherry"] = {value=1,rarity="Common"},
	["Chick"] = {value=3,rarity="Common"},
	["Choco"] = {value=100,rarity="Common"},
	["Clan"] = {value=1,rarity="Common"},
	["Clown (Gun)"] = {value=1,rarity="Common"},
	["Clown (Knife)"] = {value=1,rarity="Common"},
	["Clownfish (Gun)"] = {value=2,rarity="Common"},
	["Clownfish (Knife)"] = {value=3,rarity="Common"},
	["Coal"] = {value=3,rarity="Common"},
	["Coal (Gun) [XMAS2018]"] = {value=3,rarity="Common"},
	["Coal (Gun) [XMAS2021]"] = {value=3,rarity="Common"},
	["Coal (Gun) [XMAS2022]"] = {value=3,rarity="Common"},
	["Coal (Knife) [XMAS2018]"] = {value=15,rarity="Common"},
	["Coal (Knife) [XMAS2021]"] = {value=9,rarity="Common"},
	["Coal (Knife) [XMAS2022]"] = {value=2,rarity="Common"},
	["Coconut"] = {value=2,rarity="Common"},
	["Cold"] = {value=1,rarity="Common"},
	["Combat"] = {value=1,rarity="Common"},
	["Combat II"] = {value=10,rarity="Common"},
	["Copper"] = {value=1,rarity="Common"},
	["Corl"] = {value=4,rarity="Common"},
	["Cracks (Gun)"] = {value=6,rarity="Common"},
	["Cracks (Knife)"] = {value=3,rarity="Common"},
	["Darkness (Gun)"] = {value=3,rarity="Common"},
	["Darkness (Knife)"] = {value=6,rarity="Common"},
	["Denis"] = {value=4,rarity="Common"},
	["Dolphins"] = {value=2,rarity="Common"},
	["Duckies"] = {value=2,rarity="Common"},
	["Eco"] = {value=1,rarity="Common"},
	["Ecto"] = {value=25,rarity="Common"},
	["Egg"] = {value=100,rarity="Common"},
	["Elf (2017)"] = {value=3,rarity="Common"},
	["Elf (2018)"] = {value=20,rarity="Common"},
	["Elf (2023)"] = {value=2,rarity="Common"},
	["Elf (Gun)"] = {value=100,rarity="Common"},
	["Elf (Knife)"] = {value=15,rarity="Common"},
	["Engraved"] = {value=1,rarity="Common"},
	["Etched"] = {value=8,rarity="Common"},
	["Euro"] = {value=4,rarity="Common"},
	["Eyeball"] = {value=2,rarity="Common"},
	["Fall"] = {value=2,rarity="Common"},
	["Fallout"] = {value=1,rarity="Common"},
	["Fragile (Gun)"] = {value=6,rarity="Common"},
	["Fragile (Knife)"] = {value=6,rarity="Common"},
	["Frosted (Gun)"] = {value=100,rarity="Common"},
	["Frosted (Knife)"] = {value=30,rarity="Common"},
	["Frozen (Gun)"] = {value=2,rarity="Common"},
	["Frozen (Knife)"] = {value=3,rarity="Common"},
	["Ghosts (2023)"] = {value=3,rarity="Common"},
	["Ghosts (2024)"] = {value=2,rarity="Common"},
	["Ghosty"] = {value=3,rarity="Common"},
	["Ghoulish"] = {value=90,rarity="Common"},
	["Gift Bag (Gun)"] = {value=6,rarity="Common"},
	["Gift Bag (Knife)"] = {value=75,rarity="Common"},
	["Gifts (2024)"] = {value=3,rarity="Common"},
	["Gifts (Gun)"] = {value=50,rarity="Common"},
	["Gifts (Knife)"] = {value=95,rarity="Common"},
	["Giftwrap"] = {value=2,rarity="Common"},
	["Glitch1"] = {value=65,rarity="Common"},
	["Glitch2"] = {value=35,rarity="Common"},
	["Goo"] = {value=100,rarity="Common"},
	["Grave (Gun)"] = {value=1,rarity="Common"},
	["Grave (Knife)"] = {value=1,rarity="Common"},
	["Green"] = {value=1,rarity="Common"},
	["Grind"] = {value=2,rarity="Common"},
	["HL2"] = {value=1,rarity="Common"},
	["Hardened"] = {value=1,rarity="Common"},
	["Haunted"] = {value=2,rarity="Common"},
	["Haunted (2025)"] = {value=3,rarity="Common"},
	["Haunted (Gun)"] = {value=1,rarity="Common"},
	["Haunted (Knife)"] = {value=1,rarity="Common"},
	["Hearts"] = {value=100,rarity="Common"},
	["Hearts (2026)"] = {value=2,rarity="Common"},
	["Hot Chocolate"] = {value=3,rarity="Common"},
	["Hunter"] = {value=75,rarity="Common"},
	["Ice"] = {value=1,rarity="Common"},
	["Igloo (Gun)"] = {value=3,rarity="Common"},
	["Igloo (Knife)"] = {value=2,rarity="Common"},
	["Indy"] = {value=2,rarity="Common"},
	["Infected"] = {value=75,rarity="Common"},
	["Infected (Gun)"] = {value=3,rarity="Common"},
	["Infected (Knife)"] = {value=100,rarity="Common"},
	["Infiltrator"] = {value=1,rarity="Common"},
	["Iron"] = {value=1,rarity="Common"},
	["Juice"] = {value=1,rarity="Common"},
	["Leaf"] = {value=1,rarity="Common"},
	["Leaves [HALLOWS2023]"] = {value=2,rarity="Common"},
	["Leaves [SUMMER2025]"] = {value=2,rarity="Common"},
	["Lights (Gun)"] = {value=2,rarity="Common"},
	["Lights (Knife)"] = {value=2,rarity="Common"},
	["Linked"] = {value=1,rarity="Common"},
	["Log"] = {value=1,rarity="Common"},
	["Love (2023)"] = {value=9,rarity="Common"},
	["Love (Knife)"] = {value=1,rarity="Common"},
	["Lovely"] = {value=1,rarity="Common"},
	["Moon"] = {value=9,rarity="Common"},
	["Mummified"] = {value=35,rarity="Common"},
	["Neon"] = {value=75,rarity="Common"},
	["News"] = {value=1,rarity="Common"},
	["Oily"] = {value=1,rarity="Common"},
	["Ollie"] = {value=4,rarity="Common"},
	["Orange"] = {value=1,rarity="Common"},
	["Ornament"] = {value=100,rarity="Common"},
	["Ornament1"] = {value=100,rarity="Common"},
	["Ornament2 (Gun)"] = {value=100,rarity="Common"},
	["Ornament2 (Knife)"] = {value=100,rarity="Common"},
	["Ornaments (Gun)"] = {value=8,rarity="Common"},
	["Ornaments (Knife)"] = {value=6,rarity="Common"},
	["Passion"] = {value=100,rarity="Common"},
	["Patrick"] = {value=100,rarity="Common"},
	["Pea"] = {value=1,rarity="Common"},
	["Penguin"] = {value=3,rarity="Common"},
	["Peppermint (Gun)"] = {value=2,rarity="Common"},
	["Peppermint (Knife)"] = {value=2,rarity="Common"},
	["Phantom"] = {value=10,rarity="Common"},
	["Pine (Gun)"] = {value=24,rarity="Common"},
	["Pine (Knife)"] = {value=85,rarity="Common"},
	["Plaid"] = {value=2,rarity="Common"},
	["Present"] = {value=3,rarity="Common"},
	["Present (2023)"] = {value=3,rarity="Common"},
	["Prism"] = {value=12,rarity="Common"},
	["Pumpkin (2019)"] = {value=12,rarity="Common"},
	["Pumpkin (2023)"] = {value=3,rarity="Common"},
	["RB Knife"] = {value=24,rarity="Common"},
	["RIP"] = {value=17,rarity="Common"},
	["Reindeer"] = {value=2,rarity="Common"},
	["Reindeer [XMAS2025]"] = {value=3,rarity="Common"},
	["Reptile"] = {value=100,rarity="Common"},
	["Ribbon"] = {value=3,rarity="Common"},
	["Ribbons"] = {value=50,rarity="Common"},
	["Roses"] = {value=100,rarity="Common"},
	["Sand"] = {value=2,rarity="Common"},
	["Sandy"] = {value=1,rarity="Common"},
	["Sandy (Gun)"] = {value=2,rarity="Common"},
	["Santa"] = {value=3,rarity="Common"},
	["Santa (2018)"] = {value=3,rarity="Common"},
	["Santa (2023)"] = {value=3,rarity="Common"},
	["Santa (Gun)"] = {value=100,rarity="Common"},
	["Santa (Knife)"] = {value=100,rarity="Common"},
	["Scarf"] = {value=9,rarity="Common"},
	["Shaded"] = {value=1,rarity="Common"},
	["Sidewinder"] = {value=4,rarity="Common"},
	["Sketchy"] = {value=4,rarity="Common"},
	["Skool"] = {value=8,rarity="Common"},
	["Skyline"] = {value=2,rarity="Common"},
	["Slashed"] = {value=1,rarity="Common"},
	["Slate"] = {value=1,rarity="Common"},
	["Slime (Gun)"] = {value=1,rarity="Common"},
	["Slime (Knife)"] = {value=1,rarity="Common"},
	["Slimy"] = {value=20,rarity="Common"},
	["Snowball (Gun)"] = {value=2,rarity="Common"},
	["Snowball (Knife)"] = {value=2,rarity="Common"},
	["Snowfall"] = {value=2,rarity="Common"},
	["Snowflakes (Gun)"] = {value=30,rarity="Common"},
	["Snowflakes (Knife)"] = {value=50,rarity="Common"},
	["Snowman (Gun) [XMAS2018]"] = {value=25,rarity="Common"},
	["Snowman (Gun) [XMAS2022]"] = {value=6,rarity="Common"},
	["Snowman (Knife) [XMAS2018]"] = {value=3,rarity="Common"},
	["Snowman (Knife) [XMAS2022]"] = {value=2,rarity="Common"},
	["Sparkle1"] = {value=3,rarity="Common"},
	["Sparkle10"] = {value=20,rarity="Common"},
	["Sparkle2"] = {value=3,rarity="Common"},
	["Sparkle3"] = {value=3,rarity="Common"},
	["Sparkle4"] = {value=10,rarity="Common"},
	["Sparkle5"] = {value=8,rarity="Common"},
	["Sparkle6"] = {value=12,rarity="Common"},
	["Sparkle7"] = {value=18,rarity="Common"},
	["Sparkle8"] = {value=20,rarity="Common"},
	["Sparkle9"] = {value=30,rarity="Common"},
	["Spider (2023)"] = {value=2,rarity="Common"},
	["Splat"] = {value=1,rarity="Common"},
	["Splatter"] = {value=1,rarity="Common"},
	["Stainless"] = {value=1,rarity="Common"},
	["Star"] = {value=1,rarity="Common"},
	["Starfish (Gun)"] = {value=2,rarity="Common"},
	["Starfish (Knife)"] = {value=2,rarity="Common"},
	["Starry"] = {value=5,rarity="Common"},
	["Static"] = {value=1,rarity="Common"},
	["Stickers (Gun) [HALLOWS2021]"] = {value=2,rarity="Common"},
	["Stickers (Gun) [HALLOWS2024]"] = {value=2,rarity="Common"},
	["Stickers (Gun) [SUMMER2023]"] = {value=3,rarity="Common"},
	["Stickers (Gun) [SUMMER2025]"] = {value=2,rarity="Common"},
	["Stickers (Gun) [XMAS2021]"] = {value=2,rarity="Common"},
	["Stickers (Gun) [XMAS2022]"] = {value=2,rarity="Common"},
	["Stickers (Gun) [XMAS2024]"] = {value=2,rarity="Common"},
	["Stickers (Gun) [XMAS2025]"] = {value=2,rarity="Common"},
	["Stickers (Knife) [HALLOWS2021]"] = {value=2,rarity="Common"},
	["Stickers (Knife) [HALLOWS2024]"] = {value=2,rarity="Common"},
	["Stickers (Knife) [SUMMER2023]"] = {value=2,rarity="Common"},
	["Stickers (Knife) [SUMMER2025]"] = {value=2,rarity="Common"},
	["Stickers (Knife) [XMAS2021]"] = {value=2,rarity="Common"},
	["Stickers (Knife) [XMAS2022]"] = {value=3,rarity="Common"},
	["Stickers (Knife) [XMAS2024]"] = {value=2,rarity="Common"},
	["Stickers (Knife) [XMAS2025]"] = {value=2,rarity="Common"},
	["Stickers [HALLOWS2022]"] = {value=2,rarity="Common"},
	["Stickers [HALLOWS2025]"] = {value=2,rarity="Common"},
	["Stickers [THANKSGIVING2025]"] = {value=2,rarity="Common"},
	["Stockings"] = {value=6,rarity="Common"},
	["Stockings (2024)"] = {value=2,rarity="Common"},
	["Strawberries (Gun)"] = {value=2,rarity="Common"},
	["Strawberries (Knife)"] = {value=2,rarity="Common"},
	["Striped (Gun)"] = {value=2,rarity="Common"},
	["Striped (Knife)"] = {value=2,rarity="Common"},
	["Sub"] = {value=4,rarity="Common"},
	["Sweetheart"] = {value=100,rarity="Common"},
	["TNL"] = {value=75,rarity="Common"},
	["Tailslide"] = {value=7,rarity="Common"},
	["Tourist"] = {value=2,rarity="Common"},
	["Toy (Gun)"] = {value=3,rarity="Common"},
	["Toy (Knife)"] = {value=6,rarity="Common"},
	["Trees"] = {value=6,rarity="Common"},
	["Tulip"] = {value=100,rarity="Common"},
	["UFOs (Gun)"] = {value=2,rarity="Common"},
	["UFOs (Knife)"] = {value=3,rarity="Common"},
	["Valentine"] = {value=100,rarity="Common"},
	["Vines (Gun)"] = {value=2,rarity="Common"},
	["Vines (Knife)"] = {value=3,rarity="Common"},
	["Watcher (Gun)"] = {value=3,rarity="Common"},
	["Watcher (Knife)"] = {value=2,rarity="Common"},
	["Wavy (Gun)"] = {value=3,rarity="Common"},
	["Wavy (Knife)"] = {value=3,rarity="Common"},
	["Webbed (Gun)"] = {value=25,rarity="Common"},
	["Webbed (Knife)"] = {value=100,rarity="Common"},
	["Webs"] = {value=6,rarity="Common"},
	["Whiteout"] = {value=1,rarity="Common"},
	["Witch"] = {value=100,rarity="Common"},
	["Wood"] = {value=2,rarity="Common"},
	["Wrapped (Gun)"] = {value=30,rarity="Common"},
	["Wrapped (Knife)"] = {value=3,rarity="Common"},
	["Xbox"] = {value=2,rarity="Common"},
	["Yellow"] = {value=1,rarity="Common"},
	["Zombie"] = {value=10,rarity="Common"},
}

_0x11.Vintages = {
	["America"] = {value=7,rarity="Vintage"},
	["Blood"] = {value=8,rarity="Vintage"},
	["Cowboy"] = {value=4,rarity="Vintage"},
	["Ghost"] = {value=8,rarity="Vintage"},
	["Golden"] = {value=4,rarity="Vintage"},
	["Laser"] = {value=8,rarity="Vintage"},
	["Phaser"] = {value=5,rarity="Vintage"},
	["Prince"] = {value=6,rarity="Vintage"},
	["Shadow"] = {value=6,rarity="Vintage"},
	["Splitter"] = {value=3,rarity="Vintage"},
}

_0x11.Uniques = {
	["Corrupt"] = {value=350,rarity="Unique"},
}

_0x11.Pets = {
	["<3"] = {value=7,rarity="Pet"},
	["Badger"] = {value=1,rarity="Pet"},
	["Bat"] = {value=6,rarity="Pet"},
	["Bear"] = {value=3,rarity="Pet"},
	["Black Cat"] = {value=75,rarity="Pet"},
	["Blue Pumpkin [HALLOWS2018]"] = {value=220,rarity="Pet"},
	["Blue Pumpkin [HALLOWS2019]"] = {value=1,rarity="Pet"},
	["Blue Pumpkin [HALLOWS2020]"] = {value=7,rarity="Pet"},
	["Bunny"] = {value=0,rarity="Pet"},
	["Carrot Bunny"] = {value=75,rarity="Pet"},
	["Cat"] = {value=1,rarity="Pet"},
	["Chilly"] = {value=3,rarity="Pet"},
	["Deathspeaker"] = {value=75,rarity="Pet"},
	["Dog"] = {value=1,rarity="Pet"},
	["Dogey"] = {value=150,rarity="Pet"},
	["Electro"] = {value=75,rarity="Pet"},
	["Elf"] = {value=25,rarity="Pet"},
	["Elf (2019)"] = {value=625,rarity="Pet"},
	["Elitey"] = {value=3,rarity="Pet"},
	["Eyeball"] = {value=3,rarity="Pet"},
	["Fairy"] = {value=3,rarity="Pet"},
	["Fire Bat"] = {value=50,rarity="Pet"},
	["Fire Bear"] = {value=50,rarity="Pet"},
	["Fire Bunny"] = {value=50,rarity="Pet"},
	["Fire Cat"] = {value=50,rarity="Pet"},
	["Fire Dog"] = {value=50,rarity="Pet"},
	["Fire Fox"] = {value=50,rarity="Pet"},
	["Fire Pig"] = {value=50,rarity="Pet"},
	["Fox"] = {value=2,rarity="Pet"},
	["Frostbird"] = {value=75,rarity="Pet"},
	["Ghosty"] = {value=0,rarity="Pet"},
	["Green Pumpkin [HALLOWS2018]"] = {value=60,rarity="Pet"},
	["Green Pumpkin [HALLOWS2019]"] = {value=3,rarity="Pet"},
	["Green Pumpkin [HALLOWS2020]"] = {value=12,rarity="Pet"},
	["Green Pumpkin [HALLOWS2021]"] = {value=10,rarity="Pet"},
	["Ice Phoenix"] = {value=75,rarity="Pet"},
	["Icey"] = {value=75,rarity="Pet"},
	["Jetstream"] = {value=3,rarity="Pet"},
	["Lil' Alien"] = {value=1,rarity="Pet"},
	["Mechbug"] = {value=3,rarity="Pet"},
	["Mr. Reindeer"] = {value=55,rarity="Pet"},
	["Mr. Snowman"] = {value=20,rarity="Pet"},
	["Nobledragon"] = {value=5,rarity="Pet"},
	["Overseer Eye"] = {value=3,rarity="Pet"},
	["Pengy"] = {value=3,rarity="Pet"},
	["Phoenix"] = {value=75,rarity="Pet"},
	["Pig"] = {value=2,rarity="Pet"},
	["Piggy"] = {value=55,rarity="Pet"},
	["Pumpkin (2017)"] = {value=55,rarity="Pet"},
	["Pumpkin (2018)"] = {value=50,rarity="Pet"},
	["Pumpkin (2019)"] = {value=9,rarity="Pet"},
	["Pumpkin (2020)"] = {value=2,rarity="Pet"},
	["Pumpkin (2021)"] = {value=1,rarity="Pet"},
	["Purple Pumpkin [HALLOWS2018]"] = {value=3,rarity="Pet"},
	["Red Pumpkin [HALLOWS2018]"] = {value=120,rarity="Pet"},
	["Red Pumpkin [HALLOWS2019]"] = {value=3,rarity="Pet"},
	["Red Pumpkin [HALLOWS2020]"] = {value=20,rarity="Pet"},
	["Red Pumpkin [HALLOWS2021]"] = {value=17,rarity="Pet"},
	["Reindeer"] = {value=3,rarity="Pet"},
	["Rudolph"] = {value=3,rarity="Pet"},
	["Sammy"] = {value=75,rarity="Pet"},
	["Santa (2019)"] = {value=0,rarity="Pet"},
	["Santa Dog"] = {value=3,rarity="Pet"},
	["Scarecrow"] = {value=25,rarity="Pet"},
	["Seahorsey"] = {value=3,rarity="Pet"},
	["Shadow Pumpkin"] = {value=5,rarity="Pet"},
	["Skelly"] = {value=75,rarity="Pet"},
	["Skully"] = {value=15,rarity="Pet"},
	["Snowbear"] = {value=3,rarity="Pet"},
	["Snowman"] = {value=0,rarity="Pet"},
	["Steambird"] = {value=75,rarity="Pet"},
	["Tankie"] = {value=3,rarity="Pet"},
	["Teddy"] = {value=25,rarity="Pet"},
	["Traveller"] = {value=75,rarity="Pet"},
	["UFO"] = {value=3,rarity="Pet"},
	["Vampire Bat"] = {value=3,rarity="Pet"},
	["Zombie Dog"] = {value=750,rarity="Pet"},
}



local _0x9a = {}
for _0x47, _0x0d in pairs(_0x11) do
	for name, _0x43 in pairs(_0x0d) do
		_0x9a[string.lower(name)] = {value = _0x43.value, rarity = _0x43.rarity, _0x10 = name}
		local _0x48 = string.gsub(name, "%s*%[.-%]$", "")
		if _0x48 ~= name then
			_0x9a[string.lower(_0x48)] = {value = _0x43.value, rarity = _0x43.rarity, _0x10 = name}
		end
	end
end
return _0x9a
